{:user {:plugin-repositories [["clojars" {:url "https://clojars.org/repo"}]]
        :dependencies [[pjstadig/humane-test-output "0.8.3"]
                       [proto-repl "0.3.1"]
                       [proto-repl-charts "0.3.2"]]
        :injections [(require 'pjstadig.humane-test-output)
                     (pjstadig.humane-test-output/activate!)]
        :git-dependencies [["https://github.com/tobyhede/monger.git"]]
        :plugins [[cider/cider-nrepl                 "0.18.0"]
                  [refactor-nrepl                    "2.4.0"]
                  [com.jakemccrary/lein-test-refresh "0.23.0"]
                  [camechis/deploy-uberjar           "0.3.0"]
                  [walmartlabs/vizdeps               "0.1.6"]
                  [lein-cljfmt                       "0.6.1"]
                  [lein-kibit                        "0.1.6"]
                  [lein-cloverage                    "1.0.13"]
                  [lein-licenses                     "0.2.2"]
                  [lein-autoexpect                   "1.9.0"]
                  [lein-bikeshed                     "0.5.1"]
                  [jonase/eastwood                   "0.2.9"]
                  [lein-ancient                      "0.6.15"]
                  [s3-wagon-private                  "1.3.2"]
                  [lein-pprint                       "RELEASE"]
                  [venantius/yagni                   "0.1.7"]
                  [lein-shell                        "RELEASE"]]
        :test-refresh {:notify-command ["terminal-notifier" "-title" "Tests" "-message"]}}}
